### ISSUE TITLE
识别区域无文字内容会导致崩溃

### ISSUE THREAD

**Issue by Echoosx** [GayWindTech/TransAssistant#2]
当识别区域内没有文字时，使用OCR功能后会导致崩溃，报错如下
```
Traceback (most recent call last):
  File "GUI.py", line 228, in getOCRText
    self.OCRText = getOCRResult(getScreenshot(self.ScreenPos))
  File "\TransAssistant\OCR.py", line 149, in getOCRResult
    return formatJson(finalResult)
  File "\TransAssistant\OCR.py", line 128, in formatJson
    for eachLines in eachPages['lines']:
KeyError: 'lines'
```

**Comment by CberYellowstone** [comment]
fix in 8b60e345e6c90d434d2eb9bfe991badda32e875f
