### ISSUE TITLE
选区问题

### ISSUE THREAD

**Issue by Echoosx** [GayWindTech/TransAssistant#6]
1. 使用`Enter`与`Esc`键都可以确认选区
2. 使用`c`键取消选区后，再使用OCR功能会导致崩溃，报错如下：
```
Traceback (most recent call last):
  File "GUI.py", line 237, in getOCRText
    self.OCRText = getOCRResult(getScreenshot(self.ScreenPos))
  File "D:\GitHub\Fork\TransAssistant\Screenshot.py", line 27, in getScreenshot
    Screenshot = cv2.cvtColor(np.asarray(Screenshot), cv2.COLOR_RGB2BGR)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 675, in __array__
    new["data"] = self.tobytes()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 722, in tobytes
    e.setimage(self.im)
SystemError: tile cannot extend outside image
```

**Comment by CberYellowstone** [comment]
close with 48309da
